// @vitest-environment node

import { describe, expect, test } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

const repoRoot = path.resolve(import.meta.dirname, '../..')
const adrRoot = path.join(repoRoot, 'docs/adr')

function read(name: string): string {
  return fs.readFileSync(path.join(adrRoot, name), 'utf8')
}

describe('foundational architecture decisions', () => {
  const decisions = [
    'ADR-001-core-product-scope.md',
    'ADR-002-tokenizer-and-syntax-tree.md',
    'ADR-003-memory-and-result-ownership.md',
    'ADR-004-transform-safety-classes.md',
    'ADR-005-preprocessor-strategy.md',
    'ADR-006-browser-target-query-language.md',
    'ADR-007-source-map-policy-for-generated-nodes.md',
    'ADR-010-autonomous-model-requirement.md',
    'ADR-011-native-plugin-contract.md',
    'ADR-012-canonical-preprocessor-host.md',
  ]

  test.each(decisions)('%s is accepted and records consequences', name => {
    const adr = read(name)

    expect(adr).toMatch(/^# ADR-\d{3}:/)
    expect(adr).toMatch(/- Status: Accepted/)
    expect(adr).toMatch(/- Date: \d{4}-\d{2}-\d{2}/)
    expect(adr).toContain('## Context')
    expect(adr).toContain('## Decision')
    expect(adr).toContain('## Consequences')
  })

  test('limits stable product scope to standards-oriented CSS', () => {
    const adr = read('ADR-001-core-product-scope.md')

    expect(adr).toContain('standards-oriented CSS')
    expect(adr).toContain('Explicit non-goals')
    expect(adr).toMatch(/SCSS.*experimental/s)
    expect(adr).toMatch(/performance claims.*withdrawn/i)
  })

  test('defines a spec-oriented tokenizer and lossless syntax boundary', () => {
    const adr = read('ADR-002-tokenizer-and-syntax-tree.md')

    expect(adr).toContain('https://drafts.csswg.org/css-syntax/')
    expect(adr).toContain('byte offsets')
    expect(adr).toContain('lossless component values')
    expect(adr).toContain('must not perform transforms')
  })

  test('defines compilation and result ownership without hidden allocator coupling', () => {
    const adr = read('ADR-003-memory-and-result-ownership.md')

    expect(adr).toContain('compilation-scoped arena')
    expect(adr).toContain('caller-owned allocator')
    expect(adr).toContain('CompileResult.deinit')
    expect(adr).toContain('Public compile facade')
    expect(adr).toContain('borrowed canonical target query')
    expect(adr).toContain('retain authored span order and duplicates')
    expect(adr).toContain('module_exports = null')
    expect(adr).toContain('allocator-failure')
  })

  test('makes transform authority explicit and deny-by-default', () => {
    const adr = read('ADR-004-transform-safety-classes.md')

    expect(adr).toContain('Immutable pass handoff')
    expect(adr).toContain('lossless_cleanup')
    expect(adr).toContain('Safety classes are not an ordered permission ladder')
    expect(adr).toContain('defaults to verified analysis only')
    expect(adr).toContain('https://drafts.csswg.org/css-values-4/')
    expect(adr).toContain('https://www.w3.org/TR/css-typed-om-1/')
    expect(adr).toContain('caller-owned flat postfix instruction stream')
    expect(adr).toContain('`VAL-001` supplies type evidence only')
    expect(adr).toContain('`MATH-001` evaluates the postfix evidence with a bounded stack')
    expect(adr).toContain('results that are not strictly shorter all retain the exact input root')
    expect(adr).toContain('stable CLI reaches it only through the closed verified optimizer preset')
    expect(adr).toContain('https://drafts.csswg.org/css-color-4/')
    expect(adr).toContain('A non-opaque `rgba()` or `transparent` value is not changed into alpha-hex')
    expect(adr).toContain('complete positive-zero length dimension')
    expect(adr).toContain('one structured generated-value union')
    expect(adr).toContain('`--optimize` through one static `verified-optimizer` registry')
    expect(adr).toContain('at most 32 parse-transform-emit rounds')
    expect(adr).toContain('no source-map option')
    expect(adr).toContain('`conservative-dead-code-extraction`')
    expect(adr).toContain('closed selector-matching render tree')
    expect(adr).toContain('https://drafts.csswg.org/css-nesting/')
    expect(adr).toContain('zero-output generated proof')
    expect(adr).toContain('allow_extraction')
    expect(adr).toContain('allow_experimental')
  })

  test('maps generated syntax only to an explicit causal source span', () => {
    const adr = read('ADR-007-source-map-policy-for-generated-nodes.md')

    expect(adr).toContain('explicit nonempty causal source span')
    expect(adr).toContain('one mapping at the first generated byte')
    expect(adr).toContain('does not emit fabricated per-token or per-character mappings')
    expect(adr).toContain('receives no mapping')
    expect(adr).toContain('structured AST data, not trusted raw CSS byte strings')
  })

  test('keeps native plugins deterministic borrowed transactional and experimental', () => {
    const adr = read('ADR-011-native-plugin-contract.md')

    expect(adr).toContain('trusted, Zig-only, in-process callback contract')
    expect(adr).toContain('must begin with `plugin.`')
    expect(adr).toContain('phase, then ascending numeric priority, then bytewise stable ID')
    expect(adr).toContain('borrowed only for synchronous `compile`')
    expect(adr).toContain('API0002')
    expect(adr).toContain('API0003')
    expect(adr).toContain('publishes no candidate root')
    expect(adr).toContain('not a stable plugin ABI')
  })

  test('chooses one strict strategy for every inherited format adapter', () => {
    const adr = read('ADR-005-preprocessor-strategy.md')

    expect(adr).toContain('structured diagnostic and no partial CSS')
    expect(adr).toContain('must not feed transformed bytes into the inherited parser')
    expect(adr).toContain('`limited-native-subset`')
    expect(adr).toContain('`remove-until-funded`')
    for (const id of [
      'scss',
      'sass',
      'less',
      'stylus',
      'css-modules',
      'css-in-js',
      'postcss',
      'tailwind',
    ]) {
      expect(adr).toContain(`| \`${id}\` |`)
    }
  })

  test('funds version-pinned canonical preprocessors behind one bounded host', () => {
    const adr = read('ADR-012-canonical-preprocessor-host.md')

    expect(adr).toContain('`zigcss-preprocessor-v1`')
    expect(adr).toContain('`sass` `1.101.0`')
    expect(adr).toContain('`less` `4.6.7`')
    expect(adr).toContain('`stylus` `0.64.0`')
    expect(adr).toContain('MIT')
    expect(adr).toContain('Apache-2.0')
    expect(adr).toContain('full language compatibility')
    expect(adr).toContain('trusted-project-code mode')
    expect(adr).toContain('must not perform network access')
    expect(adr).toContain('remain unavailable until')
  })

  test('defines deterministic explicit targets and pinned generated compatibility data', () => {
    const adr = read('ADR-006-browser-target-query-language.md')

    expect(adr).toContain('chrome')
    expect(adr).toContain('optional-whitespace ">="')
    expect(adr).toContain('not Browserslist syntax')
    expect(adr).toContain('@mdn/browser-compat-data` 8.0.0')
    expect(adr).toContain('manifest and normalized-data SHA-256')
    expect(adr).toContain('annotated result remains explicit')
    expect(adr).toContain('Zig library and test-only pass driver')
    expect(adr).toContain('`compatibility_rewrite`')
    expect(adr).toContain('https://drafts.csswg.org/css-cascade-5/')
    expect(adr).toContain('https://drafts.csswg.org/selectors/')
    expect(adr).toContain('standard-last ordering')
    expect(adr).toContain('separate adjacent style rules')
    expect(adr).toContain('manual vendor form')
    expect(adr).toContain('stable recovery CLI')
  })

  test('makes the approved model and single-agent rule a hard autonomous gate', () => {
    const adr = read('ADR-010-autonomous-model-requirement.md')

    expect(adr).toContain('gpt-5.6-sol')
    expect(adr).toContain('xhigh reasoning')
    expect(adr).toContain('one implementation agent')
    expect(adr).toContain('No fallback model')
  })
})
