// @vitest-environment node

import { describe, expect, test } from 'vitest'
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'

const repoRoot = path.resolve(import.meta.dirname, '../..')
const orientScript = path.join(repoRoot, 'scripts/autodevelop/orient.sh')
const controlScript = path.join(repoRoot, 'scripts/autodevelop/ctl.sh')
const launchScript = path.join(repoRoot, 'scripts/autodevelop/launch-loop.sh')
const loopScript = path.join(repoRoot, 'scripts/autodevelop/loop.sh')
const passScript = path.join(repoRoot, 'scripts/autodevelop/run-pass.sh')
const pushScript = path.join(repoRoot, 'scripts/autodevelop/push-checkpoint.sh')
const selftestScript = path.join(repoRoot, 'scripts/autodevelop/selftest.sh')
const protocolPath = path.join(repoRoot, 'docs/operations/codex-loop-protocol.md')

describe('autonomous development operations', () => {
  test('orientation is executable, read-only, and reconstructs durable state', () => {
    const before = execFileSync('git', ['status', '--porcelain=v1'], { cwd: repoRoot, encoding: 'utf8' })
    const output = execFileSync('bash', [orientScript], { cwd: path.join(repoRoot, 'docs'), encoding: 'utf8' })
    const after = execFileSync('git', ['status', '--porcelain=v1'], { cwd: repoRoot, encoding: 'utf8' })

    expect(fs.statSync(orientScript).mode & 0o111).not.toBe(0)
    expect(after).toBe(before)
    expect(output).toContain('ZigCSS autonomous development orientation')
    expect(output).toContain('## branch and working tree')
    expect(output).toContain('## current ledger work')
    expect(output).toContain('## release convergence control')
    expect(output).toContain('## active blockers')
    expect(output).toContain('## last full validation')
    expect(output).toContain('DEVELOPMENT_PLAN.md')
  })

  test('protocol preserves the approved authority and package loop', () => {
    const protocol = fs.readFileSync(protocolPath, 'utf8')

    expect(protocol).toContain('one implementation agent')
    expect(protocol).toContain('DEVELOPMENT_PLAN.md')
    expect(protocol).toContain('DEVELOPMENT_STATUS.md')
    expect(protocol).toMatch(/reproduce or measure/i)
    expect(protocol).toMatch(/add or strengthen tests/i)
    expect(protocol).toMatch(/smallest correct change/i)
    expect(protocol).toContain('automatically pushes')
    expect(protocol).toContain('Milestone 10, `NATIVE-009`, and `REL-010` are verified')
    expect(protocol).toContain('current autonomous program is complete')
    expect(protocol).toContain('`BENCH-007` is deferred external')
    expect(protocol).toContain('no project-funded infrastructure')
    expect(protocol).toContain("owner's 2026-08-18 stable-promotion authorization")
    expect(protocol).toContain('non-prerelease GitHub Release, npm `latest`, and the existing GitHub Pages site')
    expect(protocol).toContain('It may not move or recreate `v0.6.0-rc.2`')
    expect(protocol).toContain('scripts/autodevelop/orient.sh')
    expect(protocol).toContain('scripts/autodevelop/ctl.sh')
    expect(protocol).toContain('atomic directory lock')
    expect(protocol).toContain('BLOCKED <stable-code>: <reason>')
    expect(protocol).toContain('finite release-gap inventory')
    expect(protocol).toContain('After four consecutive reductions')
    expect(protocol).toContain('integrates `main` after four green passes')
    expect(protocol).toContain('closed `NATIVE-007` five-target hosted-validation terminal')
  })

  test('single-lane supervisor pins the model and passes hermetic control tests', () => {
    const before = execFileSync('git', ['status', '--porcelain=v1'], { cwd: repoRoot, encoding: 'utf8' })
    const selftest = execFileSync('bash', [selftestScript], { cwd: repoRoot, encoding: 'utf8' })
    const prompt = execFileSync('bash', [passScript, '--print-prompt'], { cwd: repoRoot, encoding: 'utf8' })
    const after = execFileSync('git', ['status', '--porcelain=v1'], { cwd: repoRoot, encoding: 'utf8' })
    const control = fs.readFileSync(controlScript, 'utf8')
    const loop = fs.readFileSync(loopScript, 'utf8')
    const push = fs.readFileSync(pushScript, 'utf8')

    for (const script of [controlScript, launchScript, loopScript, passScript, pushScript, selftestScript]) {
      expect(fs.statSync(script).mode & 0o111).not.toBe(0)
    }
    expect(after).toBe(before)
    expect(selftest).toContain('PASS=105 FAIL=0')
    expect(prompt).toContain('Use only gpt-5.6-sol with max reasoning')
    expect(prompt).toContain('Never delegate, spawn subagents, create child tasks, or fall back')
    expect(prompt).toContain('Milestone 10, NATIVE-009, and the REL-010 stable v0.6.0 publication terminal are verified and closed')
    expect(prompt).toContain('The current autonomous program is complete under ADR-016')
    expect(prompt).toContain('BENCH-007 is deferred external')
    expect(prompt).toContain('Do not provision infrastructure or spend project funds')
    expect(prompt).toContain('emit COMPLETE after read-only orientation')
    expect(prompt).not.toContain('Only BENCH-007 remains')
    expect(prompt).not.toContain('stable code controlled-benchmark-archive')
    expect(prompt).toContain('Do not push ordinary branch checkpoints from this model pass')
    expect(prompt).toContain('Stable publication authority was successfully consumed and closed')
    expect(prompt).toContain('Never move, delete, recreate, or republish `v0.6.0-rc.2`, `v0.6.0`, npm `0.6.0-rc.2`, or npm `0.6.0`')
    expect(prompt).not.toContain('REL-010 stable-promotion sequence is active')
    expect(prompt).toContain('ZIGCSS-AUTODEVELOP-STATUS: PROGRESS <short summary>')
    expect(prompt).toContain('ZIGCSS-AUTODEVELOP-GAP: <work-package> <stable-family> <REDUCED|CLOSED>')
    expect(prompt).toContain('A sibling search is inspection, not an automatic work queue')
    expect(control).toContain('doctor|test|run|start|stop|pause|resume|status|logs|orient')
    expect(control).toContain('screen -dmS')
    expect(control).not.toMatch(/Library\/LaunchAgents|launchctl|git\s+push|npm\s+publish/)
    expect(loop).toContain('blocked attempt $BLOCKED_COUNT/3')
    expect(loop).toContain('autodevelop_record_blocker "$BLOCKER_CODE"')
    expect(loop).toContain('consecutive-errors')
    expect(loop).toContain('push_green_checkpoint || break')
    expect(loop).toContain('push_green_checkpoint --recovery-only')
    expect(loop).toContain('AUTODEVELOP_MAIN_BATCH_PASSES')
    expect(push).toContain('push --porcelain')
    expect(push).toContain('--recovery-only')
    expect(push).toContain('ls-remote --exit-code')
    expect(push).not.toMatch(/--force(?:-with-lease)?/)
  }, 15_000)
})
