// Generated by scripts/generate-prefix-data.mjs. Do not edit by hand.
const types = @import("compatibility_types.zig");

pub const source = types.SourceMetadata{
    .package = "@mdn/browser-compat-data",
    .version = "8.0.0",
    .git_commit = "d256a4fd553dbc52d651d49d8b2eb660b027efe3",
    .released_at = "2026-05-22T15:22:43.751Z",
    .tarball_sha1 = "af766e2af1c846a94d58d5931b15c37a914200a3",
    .tarball_integrity = "sha512-VS5jxDp3MxneNPtrueJhktBn+iB5ZlSLYZyAVZPXDYjhTrD/o8cGtRiuEdQoNZidUiUBh6K87wRTbWe2164iag==",
    .license = "CC0-1.0",
    .repository = "https://github.com/mdn/browser-compat-data",
    .manifest_sha256 = "ef1aa17550bb1ef19ef8d8de52e1bf865ad93a5b8209ff234a646b6595385503",
    .selected_data_sha256 = "6864f53473204a5bd6b43985d52a4d92c54c809b685aeb2eea82c15ef0e3641b",
};

const support_0 = [_]types.SupportStatement{
    .{ .browser = .chrome, .added = .{ .major = 43, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .chrome, .added = .{ .major = 1, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 12, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 16, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 49, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 5, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-moz-" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 9, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 4, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 9, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 4, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .ie, .added = .{ .major = 10, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
};

const support_1 = [_]types.SupportStatement{
    .{ .browser = .chrome, .added = .{ .major = 84, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .chrome, .added = .{ .major = 1, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 84, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 12, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 80, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 64, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 1, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-moz-" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 15, .minor = 4, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 3, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 15, .minor = 4, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 1, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
};

const support_2 = [_]types.SupportStatement{
    .{ .browser = .chrome, .added = .{ .major = 76, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 79, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 17, .minor = 0, .patch = 0 }, .removed = .{ .major = 79, .minor = 0, .patch = 0 }, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 103, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = true },
    .{ .browser = .safari, .added = .{ .major = 18, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 9, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 18, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 9, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
};

const support_3 = [_]types.SupportStatement{
    .{ .browser = .chrome, .added = .{ .major = 54, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .chrome, .added = .{ .major = 1, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 79, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 12, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 12, .minor = 0, .patch = 0 }, .removed = .{ .major = 79, .minor = 0, .patch = 0 }, .form = .{ .kind = .prefix, .value = "-ms-" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 69, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 49, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 1, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-moz-" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 3, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 2, .minor = 0, .patch = 0 }, .removed = .{ .major = 3, .minor = 0, .patch = 0 }, .form = .{ .kind = .prefix, .value = "-khtml-" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 3, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .ie, .added = .{ .major = 10, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-ms-" }, .partial = false, .annotated = false },
};

const support_4 = [_]types.SupportStatement{
    .{ .browser = .chrome, .added = .{ .major = 71, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .chrome, .added = .{ .major = 15, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .alternative_name, .value = ":-webkit-full-screen" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 12, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 64, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 9, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .alternative_name, .value = ":-moz-full-screen" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 16, .minor = 4, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 6, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .alternative_name, .value = ":-webkit-full-screen" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 16, .minor = 4, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = true, .annotated = true },
    .{ .browser = .ios_safari, .added = .{ .major = 12, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .alternative_name, .value = ":-webkit-full-screen" }, .partial = true, .annotated = true },
    .{ .browser = .ie, .added = .{ .major = 11, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-ms-" }, .partial = false, .annotated = false },
};

const support_5 = [_]types.SupportStatement{
    .{ .browser = .chrome, .added = .{ .major = 57, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .chrome, .added = .{ .major = 6, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-input-" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 79, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 12, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-input-" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 12, .minor = 0, .patch = 0 }, .removed = .{ .major = 79, .minor = 0, .patch = 0 }, .form = .{ .kind = .prefix, .value = "-ms-input-" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 51, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 19, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-moz-" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 10, .minor = 1, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 5, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-input-" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 10, .minor = 3, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 4, .minor = 2, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-input-" }, .partial = false, .annotated = false },
};

const support_6 = [_]types.SupportStatement{
    .{ .browser = .chrome, .added = .{ .major = 29, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .chrome, .added = .{ .major = 21, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 12, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 20, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = true },
    .{ .browser = .safari, .added = .{ .major = 9, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 7, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 9, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 7, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .ie, .added = .{ .major = 11, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = true, .annotated = true },
    .{ .browser = .ie, .added = .{ .major = 8, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .alternative_name, .value = "-ms-flexbox" }, .partial = true, .annotated = true },
};

const support_7 = [_]types.SupportStatement{
    .{ .browser = .chrome, .added = .{ .major = 56, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .edge, .added = .{ .major = 16, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .firefox, .added = .{ .major = 32, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 13, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .safari, .added = .{ .major = 7, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 13, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .standard, .value = "" }, .partial = false, .annotated = false },
    .{ .browser = .ios_safari, .added = .{ .major = 7, .minor = 0, .patch = 0 }, .removed = null, .form = .{ .kind = .prefix, .value = "-webkit-" }, .partial = false, .annotated = false },
};

pub const features = [_]types.Feature{
    .{ .id = "at-rule.keyframes", .kind = .at_rule, .support = &support_0 },
    .{ .id = "property.appearance", .kind = .property, .support = &support_1 },
    .{ .id = "property.backdrop-filter", .kind = .property, .support = &support_2 },
    .{ .id = "property.user-select", .kind = .property, .support = &support_3 },
    .{ .id = "selector.fullscreen", .kind = .selector, .support = &support_4 },
    .{ .id = "selector.placeholder", .kind = .selector, .support = &support_5 },
    .{ .id = "value.display.flex", .kind = .value, .support = &support_6 },
    .{ .id = "value.position.sticky", .kind = .value, .support = &support_7 },
};
