import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath, pathToFileURL } from 'node:url'

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..')

test('canonical provider policy immutably denies network and process escape surfaces', () => {
  const policy = pathToFileURL(path.join(repositoryRoot, 'preprocessor', 'network-policy.mjs')).href
  const result = spawnSync(process.execPath, ['--input-type=module', '-e', [
    "import cluster from 'node:cluster'",
    "import { fork as namedClusterFork } from 'node:cluster'",
    "import { spawnSync as namedSpawnSync } from 'node:child_process'",
    "import dgram from 'node:dgram'",
    "import dns from 'node:dns'",
    "import { Resolver as NamedDnsResolver, lookup as namedDnsLookup, setServers as namedDnsSetServers } from 'node:dns'",
    "import dnsPromises from 'node:dns/promises'",
    "import { Resolver as NamedDnsPromisesResolver, lookup as namedDnsPromisesLookup, setServers as namedDnsPromisesSetServers } from 'node:dns/promises'",
    "import http from 'node:http'",
    "import http2 from 'node:http2'",
    "import https from 'node:https'",
    "import { get as namedHttpsGet } from 'node:https'",
    "import inspector from 'node:inspector'",
    "import net from 'node:net'",
    "import { connect as namedNetConnect } from 'node:net'",
    "import { kill as namedProcessKill } from 'node:process'",
    "import tls from 'node:tls'",
    "import workerThreads from 'node:worker_threads'",
    "import { Worker as NamedWorker } from 'node:worker_threads'",
    `const { disableNetworkAccess } = await import(${JSON.stringify(policy)})`,
    'disableNetworkAccess()',
    'disableNetworkAccess()',
    "const dynamicChildProcess = await import('node:child_process')",
    "const dynamicInspectorPromises = await import('node:inspector/promises').catch(() => null)",
    'const denied = []',
    'function expectSync(label, code, operation) {',
    '  try { operation(); throw new Error(`${label} escaped`) }',
    '  catch (error) {',
    '    if (error?.message === `${label} escaped`) throw error',
    '    if (error?.code !== code) throw new Error(`${label}: ${error?.code ?? error}`)',
    '    denied.push(label)',
    '  }',
    '}',
    'async function expectAsync(label, code, operation) {',
    '  try { await operation(); throw new Error(`${label} escaped`) }',
    '  catch (error) {',
    '    if (error?.message === `${label} escaped`) throw error',
    '    if (error?.code !== code) throw new Error(`${label}: ${error?.code ?? error}`)',
    '    denied.push(label)',
    '  }',
    '}',
    "const NETWORK = 'ZIGCSS_NETWORK_DISABLED'",
    "const PROCESS = 'ZIGCSS_PROCESS_DISABLED'",
    'let coercions = 0',
    "const coercingBinding = { [Symbol.toPrimitive]() { coercions += 1; return 'tcp_wrap' } }",
    "const coercingBuiltin = { [Symbol.toPrimitive]() { coercions += 1; return 'node:child_process' } }",
    'for (const [label, operation] of [',
    "  ['worker', () => new workerThreads.Worker('0', { eval: true, execArgv: [], env: {} })],",
    "  ['worker:named', () => new NamedWorker('0', { eval: true, execArgv: [], env: {} })],",
    "  ['cluster', () => cluster.fork({ ZIGCSS_NETWORK_POLICY_CLUSTER_CHILD: '1' })],",
    "  ['cluster:named', () => namedClusterFork({ ZIGCSS_NETWORK_POLICY_CLUSTER_CHILD: '1' })],",
    "  ['child_process:named', () => namedSpawnSync(process.execPath, ['--version'], { env: {} })],",
    "  ['child_process:dynamic', () => dynamicChildProcess.spawnSync(process.execPath, ['--version'], { env: {} })],",
    "  ['child_process:constructor', () => new dynamicChildProcess.ChildProcess().spawn({ file: process.execPath, args: [process.execPath, '--version'] })],",
    "  ['inspector.open', () => inspector.open(0, '127.0.0.1')],",
    "  ['inspector.Session', () => new inspector.Session().connect()],",
    "  ['process.kill', () => process.kill(999999, 0)],",
    "  ['process.kill:named', () => namedProcessKill(999999, 0)],",
    "  ['process._kill', () => process._kill(999999, 0)],",
    "  ['process._debugProcess', () => process._debugProcess(999999)],",
    "  ['process.binding:process', () => process.binding('process_wrap')],",
    "  ['process.binding:fs', () => process.binding('fs')],",
    "  ['process.binding:boxed', () => process.binding(new String('tcp_wrap'))],",
    "  ['process.binding:coercing', () => process.binding(coercingBinding)],",
    "  ['process._linkedBinding', () => process._linkedBinding('anything')],",
    "  ['process.getBuiltinModule', () => process.getBuiltinModule('node:child_process')],",
    "  ['process.getBuiltinModule:boxed', () => process.getBuiltinModule(new String('node:child_process'))],",
    "  ['process.getBuiltinModule:coercing', () => process.getBuiltinModule(coercingBuiltin)],",
    "  ['process.dlopen', () => process.dlopen({}, '/definitely/missing.node')],",
    ']) expectSync(label, PROCESS, operation)',
    "if (dynamicInspectorPromises !== null) expectSync('inspector.promises.open', PROCESS, () => dynamicInspectorPromises.open(0, '127.0.0.1'))",
    "if (dynamicInspectorPromises !== null) expectSync('inspector.promises.Session', PROCESS, () => new dynamicInspectorPromises.Session().connect())",
    "if (typeof process.execve === 'function') expectSync('process.execve', PROCESS, () => process.execve('/definitely/missing', [], {}))",
    'for (const [label, operation] of [',
    "  ['http.get', () => http.get('http://example.invalid')],",
    "  ['http.ClientRequest', () => new http.ClientRequest('http://example.invalid')],",
    "  ['http.createServer', () => http.createServer()],",
    "  ['https.get', () => https.get('https://example.invalid')],",
    "  ['https.get:named', () => namedHttpsGet('https://example.invalid')],",
    "  ['https.createServer', () => https.createServer()],",
    "  ['net.connect', () => net.connect(443, 'example.invalid')],",
    "  ['net.connect:named', () => namedNetConnect(443, 'example.invalid')],",
    "  ['net.listen', () => new net.Server().listen(0, '127.0.0.1')],",
    "  ['net._createServerHandle', () => net._createServerHandle('127.0.0.1', 0, 4, -1, 0)],",
    "  ['tls.connect', () => tls.connect(443, 'example.invalid')],",
    "  ['tls.createServer', () => tls.createServer()],",
    "  ['dgram.createSocket', () => dgram.createSocket('udp4')],",
    "  ['dgram._createSocketHandle', () => dgram._createSocketHandle('127.0.0.1', 0, 'udp4', -1, 0)],",
    "  ['http2.connect', () => http2.connect('https://example.invalid')],",
    "  ['http2.createServer', () => http2.createServer()],",
    "  ['dns.lookup', () => dns.lookup('example.invalid', () => {})],",
    "  ['dns.lookup:named', () => namedDnsLookup('example.invalid', () => {})],",
    "  ['dns.setServers', () => dns.setServers(['127.0.0.1'])],",
    "  ['dns.setServers:named', () => namedDnsSetServers(['127.0.0.1'])],",
    "  ['dns.Resolver', () => new dns.Resolver()],",
    "  ['dns.Resolver:named', () => new NamedDnsResolver()],",
    "  ['dns.promises.setServers', () => dnsPromises.setServers(['127.0.0.1'])],",
    "  ['dns.promises.setServers:named', () => namedDnsPromisesSetServers(['127.0.0.1'])],",
    "  ['dns.promises.Resolver', () => new dnsPromises.Resolver()],",
    "  ['dns.promises.Resolver:named', () => new NamedDnsPromisesResolver()],",
    "  ['process.binding:network', () => process.binding('tcp_wrap')],",
    "  ['process.getBuiltinModule:network', () => process.getBuiltinModule('node:http')],",
    ']) expectSync(label, NETWORK, operation)',
    "if (typeof dns.resolveTlsa === 'function') expectSync('dns.resolveTlsa', NETWORK, () => dns.resolveTlsa('example.invalid', () => {}))",
    "if (typeof globalThis.WebSocket === 'function') expectSync('WebSocket', NETWORK, () => new globalThis.WebSocket('ws://example.invalid'))",
    "if (typeof http.WebSocket === 'function') expectSync('http.WebSocket', NETWORK, () => new http.WebSocket('ws://example.invalid'))",
    "await expectAsync('fetch', NETWORK, () => fetch('https://example.invalid'))",
    "await expectAsync('dns.promises.lookup', NETWORK, () => dnsPromises.lookup('example.invalid'))",
    "await expectAsync('dns.promises.lookup:named', NETWORK, () => namedDnsPromisesLookup('example.invalid'))",
    "if (typeof dnsPromises.resolveTlsa === 'function') await expectAsync('dns.promises.resolveTlsa', NETWORK, () => dnsPromises.resolveTlsa('example.invalid'))",
    "assertDescriptor('http.get', http, 'get')",
    "assertDescriptor('workerThreads.Worker', workerThreads, 'Worker')",
    "assertDescriptor('process.kill', process, 'kill')",
    "assertDescriptor('dns.resolve', dns, 'resolve')",
    "assertDescriptor('fetch', globalThis, 'fetch')",
    'function assertDescriptor(label, target, name) {',
    '  const descriptor = Object.getOwnPropertyDescriptor(target, name)',
    '  if (descriptor?.configurable !== false || descriptor?.writable !== false) {',
    '    throw new Error(`${label} is mutable`)',
    '  }',
    '  if (Reflect.set(target, name, () => {})) throw new Error(`${label} accepted reassignment`)',
    '}',
    "if (typeof process.getBuiltinModule === 'function' && process.getBuiltinModule('node:url') === undefined) throw new Error('safe builtin blocked')",
    "if (!Array.isArray(dns.getServers())) throw new Error('safe DNS getter blocked')",
    "if (coercions !== 0) throw new Error(`boundary invoked ${coercions} coercion callbacks`)",
    "process.stdout.write(JSON.stringify(denied.sort()))",
  ].join('\n')], {
    encoding: 'utf8',
    env: { ...process.env, ZIGCSS_NETWORK_POLICY_CLUSTER_CHILD: '0' },
    timeout: 10_000,
  })

  assert.equal(result.error, undefined)
  assert.equal(result.status, 0, result.stderr)
  const denied = JSON.parse(result.stdout)
  for (const required of [
    'cluster',
    'child_process:constructor',
    'child_process:dynamic',
    'child_process:named',
    'dgram.createSocket',
    'dns.Resolver',
    'dns.Resolver:named',
    'dns.promises.Resolver',
    'dns.promises.Resolver:named',
    'dns.promises.lookup',
    'dns.promises.lookup:named',
    'dns.setServers',
    'dns.setServers:named',
    'fetch',
    'http.createServer',
    'http2.connect',
    'https.get',
    'https.get:named',
    'inspector.open',
    'inspector.promises.open',
    'inspector.promises.Session',
    'net._createServerHandle',
    'net.listen',
    'net.connect:named',
    'process._linkedBinding',
    'process.binding:network',
    'process.binding:boxed',
    'process.binding:coercing',
    'process.binding:process',
    'process.dlopen',
    'process.getBuiltinModule',
    'process.getBuiltinModule:boxed',
    'process.getBuiltinModule:coercing',
    'process.kill',
    'process.kill:named',
    'tls.connect',
    'worker',
    'worker:named',
  ]) {
    assert.equal(denied.includes(required), true, required)
  }
})
