const std = @import("std");
const at_rule_merge = @import("at_rule_merge.zig");
const color_zero_shortening = @import("color_zero_shortening.zig");
const emitter = @import("../css/emitter.zig");
const equivalence = @import("../css/equivalence.zig");
const duplicate_declarations = @import("duplicate_declarations.zig");
const empty_cleanup = @import("empty_cleanup.zig");
const math_folding = @import("math_folding.zig");
const pass_manager = @import("pass_manager.zig");
const pipeline = @import("../css/pipeline.zig");
const selector_rule_merge = @import("selector_rule_merge.zig");
const shorthand_synthesis = @import("shorthand_synthesis.zig");

/// Public preset identifier. This names a closed plan, not another transform
/// pass, so it never appears in pass dependency metadata.
pub const id = "verified-optimizer";
pub const max_fixed_point_rounds: usize = 32;

// Keep the registry at static lifetime: Plan borrows pointers to these pass
// definitions. Compatibility rewrites, extraction, and experimental passes
// are intentionally absent and cannot enter through dependency closure.
const registry = [_]pass_manager.Pass{
    duplicate_declarations.definition(),
    empty_cleanup.definition(),
    math_folding.definition(),
    color_zero_shortening.definition(),
    shorthand_synthesis.definition(),
    at_rule_merge.definition(),
    selector_rule_merge.definition(),
};

// Duplicate analysis is selected transitively by shorthand synthesis. Keeping
// it out of this direct request list makes the dependency edge executable.
const requested = [_][]const u8{
    empty_cleanup.id,
    math_folding.id,
    color_zero_shortening.id,
    shorthand_synthesis.id,
    at_rule_merge.id,
    selector_rule_merge.id,
};

const policy = pass_manager.Policy{
    .allow_lossless_cleanup = true,
    .allow_semantic_rewrite = true,
};

pub fn passDefinitions() []const pass_manager.Pass {
    return &registry;
}

pub fn requestedPassIds() []const []const u8 {
    return &requested;
}

pub fn buildPlan(allocator: std.mem.Allocator) pass_manager.Error!pass_manager.Plan {
    return pass_manager.buildPlan(allocator, &registry, &requested, policy);
}

/// Applies the closed plan until parse-transform-emit reaches a byte-stable
/// fixed point. Reparse rounds are bounded and deliberately expose no source
/// map: mapping generated bytes back through multiple authored snapshots needs
/// a separate composed-map proof before that API can be enabled.
pub fn applyToFixedPoint(
    allocator: std.mem.Allocator,
    parsed: *pipeline.ParsedStylesheet,
    mode: emitter.Mode,
) !void {
    return applyToFixedPointTracked(allocator, parsed, mode, null);
}

const ExecutionStats = struct {
    pass_rounds: usize = 0,
    emit_rounds: usize = 0,
    reparse_rounds: usize = 0,
};

fn applyToFixedPointTracked(
    allocator: std.mem.Allocator,
    parsed: *pipeline.ParsedStylesheet,
    mode: emitter.Mode,
    stats: ?*ExecutionStats,
) !void {
    if (parsed.hasErrors()) return error.InputHasErrors;

    const source_name = try allocator.dupe(u8, parsed.file().name);
    defer allocator.free(source_name);
    var plan = try buildPlan(allocator);
    defer plan.deinit();
    var previous: ?pipeline.CompileResult = null;
    defer if (previous) |*result| result.deinit();

    var round: usize = 0;
    while (round < max_fixed_point_rounds) : (round += 1) {
        const root_before_round = parsed.rules;
        try parsed.applyPassPlan(allocator, &plan, .{});
        if (stats) |value| value.pass_rounds += 1;

        // Every pass is immutable and acceptance-gated. Identity therefore
        // proves that the complete closed plan was a no-op; emitting and
        // reparsing cannot reveal another transform opportunity.
        if (parsed.rules == root_before_round) return;

        if (stats) |value| value.emit_rounds += 1;
        var current = try parsed.emitResult(allocator, .{ .mode = mode });

        if (previous) |*prior| {
            if (std.mem.eql(u8, prior.css, current.css)) {
                prior.deinit();
                previous = null;
                current.deinit();
                return;
            }
        }
        if (round + 1 == max_fixed_point_rounds) {
            current.deinit();
            return error.OptimizationDidNotConverge;
        }

        if (stats) |value| value.reparse_rounds += 1;
        var reparsed = pipeline.parse(allocator, source_name, current.css) catch |err| {
            current.deinit();
            return err;
        };
        if (reparsed.hasErrors()) {
            reparsed.deinit();
            current.deinit();
            return error.ValidationFailed;
        }
        parsed.deinit();
        parsed.* = reparsed;
        if (previous) |*prior| prior.deinit();
        previous = current;
    }
    unreachable;
}

test "verified optimizer is a closed acceptance-gated preset" {
    try std.testing.expectEqual(@as(usize, 7), passDefinitions().len);
    try std.testing.expectEqual(@as(usize, 6), requestedPassIds().len);

    var plan = try buildPlan(std.testing.allocator);
    defer plan.deinit();
    const expected = [_][]const u8{
        duplicate_declarations.id,
        empty_cleanup.id,
        math_folding.id,
        color_zero_shortening.id,
        shorthand_synthesis.id,
        at_rule_merge.id,
        selector_rule_merge.id,
    };
    try std.testing.expectEqual(expected.len, plan.orderedPasses().len);
    for (plan.orderedPasses(), expected) |pass, expected_id| {
        try std.testing.expectEqualStrings(expected_id, pass.metadata.id);
        try std.testing.expectEqual(pass_manager.Maturity.verified, pass.metadata.maturity);
        try std.testing.expect(pass.validate != null);
        try std.testing.expect(pass.metadata.supports_nested_rules);
        try std.testing.expectEqual(pass_manager.OrderEffect.preserves, pass.metadata.order_effect);
        try std.testing.expectEqual(pass_manager.CustomPropertyEffect.preserves, pass.metadata.custom_property_effect);
        try std.testing.expectEqual(pass_manager.LogicalPropertyEffect.preserves, pass.metadata.logical_property_effect);
        try std.testing.expect(pass.metadata.safety != .compatibility_rewrite);
        try std.testing.expect(pass.metadata.safety != .extraction);
        try std.testing.expect(pass.metadata.acceptance.postcondition);
        try std.testing.expect(pass.metadata.acceptance.idempotence);
        try std.testing.expect(pass.metadata.acceptance.allocation_failures);
        try std.testing.expect(pass.metadata.acceptance.nested_rules);
        if (pass.metadata.safety != .analysis) {
            try std.testing.expect(pass.metadata.acceptance.semantic_validation);
            try std.testing.expect(pass.metadata.acceptance.differential_validation);
        }
    }
}

fn exercisePlanAllocationFailures(allocator: std.mem.Allocator) !void {
    var plan = try buildPlan(allocator);
    defer plan.deinit();
    try std.testing.expectEqual(@as(usize, 7), plan.orderedPasses().len);
}

test "verified optimizer plan handles every allocation failure" {
    try std.testing.checkAllAllocationFailures(
        std.testing.allocator,
        exercisePlanAllocationFailures,
        .{},
    );
}

test "verified optimizer no-op fast path stops before emit and reparse" {
    var parsed = try pipeline.parse(
        std.testing.allocator,
        "no-op-fast-path.css",
        ".a{color:red}",
    );
    defer parsed.deinit();
    const original_root = parsed.rules;
    var stats: ExecutionStats = .{};

    var plan = try buildPlan(std.testing.allocator);
    defer plan.deinit();
    var proof_context = try pass_manager.Context.init(
        &parsed.compilation,
        parsed.source_id,
        std.testing.allocator,
    );
    const direct_result = try plan.run(
        &proof_context,
        original_root,
        .{ .verify_idempotence = true },
    );
    try std.testing.expect(direct_result == original_root);
    try std.testing.expectEqual(@as(usize, 1), proof_context.structuralProofEmitCount());

    try applyToFixedPointTracked(std.testing.allocator, &parsed, .minified, &stats);

    try std.testing.expect(parsed.rules == original_root);
    try std.testing.expectEqual(@as(usize, 1), stats.pass_rounds);
    try std.testing.expectEqual(@as(usize, 0), stats.emit_rounds);
    try std.testing.expectEqual(@as(usize, 0), stats.reparse_rounds);

    var result = try parsed.emitResult(std.testing.allocator, .{ .mode = .minified });
    defer result.deinit();
    try std.testing.expectEqualStrings(".a{color:red}", result.css);
}

test "verified optimizer reaches a byte-stable cross-pass fixed point" {
    const input = ".empty{}.a{color:#ffffff}.b{color:#fff}" ++
        ".c{width:calc(0px);margin-top:calc(1px + 0px);" ++
        "margin-right:calc(1px + 0px);margin-bottom:calc(1px + 0px);" ++
        "margin-left:calc(1px + 0px)}" ++
        "@media all{.x{z:1}}@media all{.y{z:1}}";
    var parsed = try pipeline.parse(std.testing.allocator, "fixed-point.css", input);
    defer parsed.deinit();
    var stats: ExecutionStats = .{};

    try applyToFixedPointTracked(std.testing.allocator, &parsed, .minified, &stats);
    var result = try parsed.emitResult(std.testing.allocator, .{ .mode = .minified });
    defer result.deinit();
    try std.testing.expectEqualStrings(
        ".a,.b{color:#fff}.c{width:0;margin:1px}@media all{.x,.y{z:1}}",
        result.css,
    );
    try std.testing.expect(stats.pass_rounds >= 2);
    try std.testing.expect(stats.emit_rounds >= 1);
    try std.testing.expectEqual(stats.emit_rounds, stats.reparse_rounds);
    try std.testing.expectEqual(stats.pass_rounds, stats.emit_rounds + 1);

    var reparsed = try pipeline.parse(std.testing.allocator, "fixed-point-output.css", result.css);
    defer reparsed.deinit();
    try std.testing.expect(try equivalence.equivalent(
        std.testing.allocator,
        parsed.file(),
        parsed.rules,
        reparsed.file(),
        reparsed.rules,
    ));
    var repeated_stats: ExecutionStats = .{};
    try applyToFixedPointTracked(std.testing.allocator, &reparsed, .minified, &repeated_stats);
    var repeated = try reparsed.emitResult(std.testing.allocator, .{ .mode = .minified });
    defer repeated.deinit();
    try std.testing.expectEqualStrings(result.css, repeated.css);
    try std.testing.expectEqual(@as(usize, 1), repeated_stats.pass_rounds);
    try std.testing.expectEqual(@as(usize, 0), repeated_stats.emit_rounds);
    try std.testing.expectEqual(@as(usize, 0), repeated_stats.reparse_rounds);
}

fn exerciseNoOpFastPathAllocationFailures(allocator: std.mem.Allocator) !void {
    var parsed = try pipeline.parse(
        allocator,
        "no-op-fast-path-oom.css",
        ".a{color:red}",
    );
    defer parsed.deinit();
    const original_root = parsed.rules;
    var stats: ExecutionStats = .{};

    try applyToFixedPointTracked(allocator, &parsed, .minified, &stats);
    try std.testing.expect(parsed.rules == original_root);
    try std.testing.expectEqual(@as(usize, 1), stats.pass_rounds);
    try std.testing.expectEqual(@as(usize, 0), stats.emit_rounds);
    try std.testing.expectEqual(@as(usize, 0), stats.reparse_rounds);
}

test "verified optimizer no-op fast path handles every allocation failure" {
    try std.testing.checkAllAllocationFailures(
        std.testing.allocator,
        exerciseNoOpFastPathAllocationFailures,
        .{},
    );
}

fn exerciseFixedPointAllocationFailures(allocator: std.mem.Allocator) !void {
    var parsed = try pipeline.parse(
        allocator,
        "fixed-point-oom.css",
        ".empty{}.a{x:1}.b{x:1}",
    );
    defer parsed.deinit();
    try applyToFixedPoint(allocator, &parsed, .minified);
    var result = try parsed.emitResult(allocator, .{ .mode = .minified });
    defer result.deinit();
    try std.testing.expectEqualStrings(".a,.b{x:1}", result.css);
}

test "verified optimizer fixed-point execution handles every allocation failure" {
    try std.testing.checkAllAllocationFailures(
        std.testing.allocator,
        exerciseFixedPointAllocationFailures,
        .{},
    );
}
