const std = @import("std");

pub const BaseDimension = enum {
    length,
    angle,
    time,
    frequency,
    resolution,
    flex,
    percent,
};

/// Closed unit taxonomy shared by parsed numeric values and structured
/// generated numeric output. `unknown` is analysis-only and is never emitted.
pub const Unit = enum {
    number,
    percent,

    // Absolute lengths.
    px,
    cm,
    mm,
    q,
    in,
    pc,
    pt,

    // Font-relative lengths.
    em,
    rem,
    ex,
    rex,
    cap,
    rcap,
    ch,
    rch,
    ic,
    ric,
    lh,
    rlh,

    // Viewport-relative lengths.
    vw,
    vh,
    vi,
    vb,
    vmin,
    vmax,
    svw,
    svh,
    svi,
    svb,
    svmin,
    svmax,
    lvw,
    lvh,
    lvi,
    lvb,
    lvmin,
    lvmax,
    dvw,
    dvh,
    dvi,
    dvb,
    dvmin,
    dvmax,

    // Container-relative lengths.
    cqw,
    cqh,
    cqi,
    cqb,
    cqmin,
    cqmax,

    deg,
    grad,
    rad,
    turn,
    s,
    ms,
    hz,
    khz,
    dpi,
    dpcm,
    dppx,
    x,
    fr,
    unknown,

    pub fn baseDimension(self: Unit) ?BaseDimension {
        return switch (self) {
            .number => null,
            .percent => .percent,
            .px,
            .cm,
            .mm,
            .q,
            .in,
            .pc,
            .pt,
            .em,
            .rem,
            .ex,
            .rex,
            .cap,
            .rcap,
            .ch,
            .rch,
            .ic,
            .ric,
            .lh,
            .rlh,
            .vw,
            .vh,
            .vi,
            .vb,
            .vmin,
            .vmax,
            .svw,
            .svh,
            .svi,
            .svb,
            .svmin,
            .svmax,
            .lvw,
            .lvh,
            .lvi,
            .lvb,
            .lvmin,
            .lvmax,
            .dvw,
            .dvh,
            .dvi,
            .dvb,
            .dvmin,
            .dvmax,
            .cqw,
            .cqh,
            .cqi,
            .cqb,
            .cqmin,
            .cqmax,
            => .length,
            .deg, .grad, .rad, .turn => .angle,
            .s, .ms => .time,
            .hz, .khz => .frequency,
            .dpi, .dpcm, .dppx, .x => .resolution,
            .fr => .flex,
            .unknown => null,
        };
    }

    /// CSS spelling used by closed generated-value serialization.
    pub fn suffix(self: Unit) ?[]const u8 {
        return switch (self) {
            .number => "",
            .percent => "%",
            .px => "px",
            .cm => "cm",
            .mm => "mm",
            .q => "q",
            .in => "in",
            .pc => "pc",
            .pt => "pt",
            .em => "em",
            .rem => "rem",
            .ex => "ex",
            .rex => "rex",
            .cap => "cap",
            .rcap => "rcap",
            .ch => "ch",
            .rch => "rch",
            .ic => "ic",
            .ric => "ric",
            .lh => "lh",
            .rlh => "rlh",
            .vw => "vw",
            .vh => "vh",
            .vi => "vi",
            .vb => "vb",
            .vmin => "vmin",
            .vmax => "vmax",
            .svw => "svw",
            .svh => "svh",
            .svi => "svi",
            .svb => "svb",
            .svmin => "svmin",
            .svmax => "svmax",
            .lvw => "lvw",
            .lvh => "lvh",
            .lvi => "lvi",
            .lvb => "lvb",
            .lvmin => "lvmin",
            .lvmax => "lvmax",
            .dvw => "dvw",
            .dvh => "dvh",
            .dvi => "dvi",
            .dvb => "dvb",
            .dvmin => "dvmin",
            .dvmax => "dvmax",
            .cqw => "cqw",
            .cqh => "cqh",
            .cqi => "cqi",
            .cqb => "cqb",
            .cqmin => "cqmin",
            .cqmax => "cqmax",
            .deg => "deg",
            .grad => "grad",
            .rad => "rad",
            .turn => "turn",
            .s => "s",
            .ms => "ms",
            .hz => "hz",
            .khz => "khz",
            .dpi => "dpi",
            .dpcm => "dpcm",
            .dppx => "dppx",
            .x => "x",
            .fr => "fr",
            .unknown => null,
        };
    }

    /// Static factor to the category's canonical unit: px, deg, s, hz, dppx,
    /// or fr. Context-dependent length units deliberately return null.
    pub fn canonicalScale(self: Unit) ?f64 {
        return switch (self) {
            .number, .percent, .px, .deg, .s, .hz, .dppx, .x, .fr => 1,
            .cm => 96.0 / 2.54,
            .mm => 96.0 / 25.4,
            .q => 96.0 / 101.6,
            .in => 96,
            .pc => 16,
            .pt => 96.0 / 72.0,
            .grad => 0.9,
            .rad => 180.0 / std.math.pi,
            .turn => 360,
            .ms => 0.001,
            .khz => 1000,
            .dpi => 1.0 / 96.0,
            .dpcm => 2.54 / 96.0,
            .em,
            .rem,
            .ex,
            .rex,
            .cap,
            .rcap,
            .ch,
            .rch,
            .ic,
            .ric,
            .lh,
            .rlh,
            .vw,
            .vh,
            .vi,
            .vb,
            .vmin,
            .vmax,
            .svw,
            .svh,
            .svi,
            .svb,
            .svmin,
            .svmax,
            .lvw,
            .lvh,
            .lvi,
            .lvb,
            .lvmin,
            .lvmax,
            .dvw,
            .dvh,
            .dvi,
            .dvb,
            .dvmin,
            .dvmax,
            .cqw,
            .cqh,
            .cqi,
            .cqb,
            .cqmin,
            .cqmax,
            .unknown,
            => null,
        };
    }
};
