pub const api = @import("api.zig");
pub const source = @import("source.zig");
pub const diagnostics = @import("diagnostics.zig");
pub const dependencies = @import("dependencies.zig");
pub const plugins = @import("plugins.zig");
pub const profiling = @import("profiling.zig");
pub const compilation = @import("compilation.zig");
pub const tokenizer = @import("tokenizer.zig");
pub const syntax = @import("syntax.zig");
pub const css = @import("css.zig");
pub const sourcemap = @import("sourcemap.zig");
pub const transform = @import("transform.zig");
pub const prefixing = @import("prefixing.zig");

pub const SourceId = source.SourceId;
pub const Span = source.Span;
pub const SourceLocation = source.Location;
pub const SourceFile = source.SourceFile;
pub const SourceManager = source.SourceManager;
pub const Diagnostic = api.Diagnostic;
pub const RawDiagnostic = diagnostics.Diagnostic;
pub const DiagnosticCode = diagnostics.Code;
pub const DiagnosticList = diagnostics.DiagnosticList;
pub const DiagnosticSeverity = diagnostics.Severity;
pub const Dependency = dependencies.Dependency;
pub const DependencyKind = dependencies.Kind;
pub const DependencyLimits = dependencies.Options;
pub const Compilation = compilation.Compilation;
pub const CompileOptions = api.CompileOptions;
pub const CompileError = api.Error;
pub const CompileResult = api.CompileResult;
pub const CompileMetrics = profiling.Metrics;
pub const CompileStageTimings = profiling.StageTimings;
pub const CompileMemoryMetrics = profiling.MemoryMetrics;
pub const OutputFormat = api.OutputFormat;
pub const SourceMapOptions = api.SourceMapOptions;
pub const ExternalSourceMapOptions = api.ExternalSourceMapOptions;
pub const TransformOptions = api.TransformOptions;
pub const PluginOptions = api.PluginOptions;
pub const ExperimentalPluginOptions = plugins.ExperimentalOptions;
pub const PluginDefinition = plugins.Definition;
pub const PluginPolicy = plugins.Policy;
pub const PluginStability = plugins.Stability;
pub const Syntax = api.Syntax;
pub const ModuleExport = api.ModuleExport;
pub const ModuleExports = api.ModuleExports;
pub const PipelineCompileResult = compilation.CompileResult;
pub const TargetQuery = prefixing.TargetQuery;
pub const compile = api.compile;
pub const Token = tokenizer.Token;
pub const TokenKind = tokenizer.TokenKind;
pub const Tokenizer = tokenizer.Tokenizer;
pub const ComponentValue = syntax.ComponentValue;
pub const ComponentValueDocument = syntax.Document;

test "public foundation types compose through the library root" {
    const std = @import("std");
    _ = api;
    _ = tokenizer;
    _ = dependencies;
    _ = plugins;
    _ = profiling;
    _ = syntax;
    _ = css;
    _ = sourcemap;
    _ = transform;
    _ = prefixing;
    var context = try Compilation.init(std.testing.allocator);
    defer context.deinit();

    const source_id = try context.addSource("public.css", ".public{}");
    const span = try Span.init(source_id, 1, 7);
    try context.report(.note, .unexpected_token, span, "public API smoke");

    const file: *const SourceFile = try context.sources.get(source_id);
    const location: SourceLocation = try file.location(span.start);
    const diagnostic: RawDiagnostic = context.diagnostics.items()[0];
    try std.testing.expectEqual(@as(u32, 1), location.line);
    try std.testing.expectEqual(DiagnosticSeverity.note, diagnostic.severity);
    try std.testing.expectEqual(DiagnosticCode.unexpected_token, diagnostic.code);
}
